obj-m += lcd_test_mod_foobar_net_klcd.o

lcd_test_mod_foobar_net_klcd-y		+= main.o

# glue code
lcd_test_mod_foobar_net_klcd-y		+= $(addprefix glue/, foobar_xmit.o \)

lcd_test_mod_foobar_net_klcd-y		+= $(addprefix ../, cap.o)

cppflags-y += $(NONISOLATED_CFLAGS)

extra-y += glue/foobar.lds

ldflags-y += -T $(LCD_TEST_MODULES_BUILD_DIR)/foobar/net_klcd/glue/foobar.lds

ccflags-y += $(NONISOLATED_CFLAGS)

