obj-m += lcd_test_mod_foobar_dummy_lcd.o

lcd_test_mod_foobar_dummy_lcd-y		+= main.o

# Original code
lcd_test_mod_foobar_dummy_lcd-y		+= dummy.o 


lcd_test_mod_foobar_dummy_lcd-y		+= $(LIBLCD)

# glue code
lcd_test_mod_foobar_dummy_lcd-y		+= $(addprefix glue/, foobar_caller.o \
						foobar_caller_dispatch.o )

lcd_test_mod_foobar_dummy_lcd-y		+= $(addprefix ../, foobar_glue_helper.o)

ccflags-y += $(ISOLATED_CFLAGS)

