		//For the following,
		//	> caller fns are in the driver (the dummy foobar module - dummy.c)
		//	> callee fns are in the foobar subsystem (the dummy subsystem that registers the module - dev.c)
module foobar() {
	projection <struct foobar_device> foobar_device {

		// attribute info for features field:
		//in - features undergoes a read in callee register_foobar (need caller to callee marshalling)
		//out - features undergoes a write in caller register_foobar (need callee to caller marshalling)
		unsigned long [in,out] features;  

		unsigned long [in,out] hw_features;
		unsigned long [out] wanted_features;
		unsigned int flags;
		projection foobar_device_ops [alloc(callee)] *foobar_device_ops;
	}

	projection <struct foobar_device_ops> foobar_device_ops {
	    rpc [in] int (*init)(projection foobar_device *dev);
	    rpc [in] void (*uninit)(projection foobar_device *dev);
	}
	rpc int register_foobar(projection foobar_device *dev);

	projection <struct foobar_device> foobar_device_unregister_foobar {
	}
	rpc void unregister_foobar(projection foobar_device_unregister_foobar *dev);

	projection <struct foobar_device> foobar_device_alloc_foobardev {
		int id;
		char name[32];
	}
	rpc projection foobar_device_alloc_foobardev [alloc(caller)] *alloc_foobardev(int id, char *name);
	
	projection <struct foobar_device> foobar_device_free_foobardev {
	}
	rpc void free_foobardev(projection foobar_device_free_foobardev [dealloc(caller)] *dev);
}
