
obj-m += lcd_test_mod_pmfs_vfs.o

# Dispatch loop, etc.
lcd_test_mod_pmfs_vfs-y              += main.o

# Glue
lcd_test_mod_pmfs_vfs-y              += $(addprefix glue/, vfs_callee.o \
							   dispatch.o \
                                                           )

lcd_test_mod_pmfs_vfs-y              += $(addprefix ../, cap.o )

cppflags-y += $(NONISOLATED_CFLAGS)
extra-y += glue/vfs_callee.lds

ldflags-y += \
	-T $(LCD_TEST_MODULES_BUILD_DIR)/pmfs/vfs_klcd/glue/vfs_callee.lds


ccflags-y += $(NONISOLATED_CFLAGS)
